### ISSUE TITLE
Removing webkit flex prefixes generates invalid css

### ISSUE THREAD

**Issue by bees** [leb2/slique#1]
Line 29 in the gulpfile:

``` javascript
.pipe(replace(/.*-webkit-box.*/g,''))
```

If the webkit prefix is the last declaration in a  rule set, the closing `}` gets removed as well. This is because the closing `}` is on the same line as the last declaration when the css is generated from the sass. You can change this behavior by adding changing the output style to expanded.

The only file that seems to be affected by this seems to be _sitewide.scss line 5.

**Comment by leb2** [comment]
Oh yeah, I forgot to put in a semicolon. Hopefully it should work now. Thanks.

**Comment by bees** [comment]
That fixed it, thanks!
